version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
        - .env
#    environment:
#      PG_DSN: ${PG_DSN}
#      ADMIN_LOGIN: ${ADMIN_LOGIN}
#      ADMIN_PASS: ${ADMIN_PASS}
#      JWT_SECRET: ${JWT_SECRET}
#      HTTP_HOST:  ${HTTP_HOST}
#      HTTP_PORT:  ${HTTP_PORT}
    ports:
      - "8080:8080"

volumes:
  pgdata: